kind: pipeline
type: docker
name: my-first-build

trigger:
  branch: 
    - test
  event:
    - push
    
steps:
  - name: build
    image: alpine
    commands:
      - echo "build step executed"
  
  - name: compile
    image: gcc
    commands:
      - g++ -o my_program main.cpp
      
  - name: deploy
    image: alpine
    commands:
      - echo "deploy step executed"
      - ./main
