kind: pipeline
type: docker
name: my-first-build

trigger:
  branch: 
    - test
  event:
    - push
    
steps:
  - name: build
    image: alpine
    commands:
      - echo "build step executed"
      - g++ -o main main.cpp
      - ./main

  - name: deploy
    image: alpine
    commands:
      - echo "deploy step executed"
      - ./main
