kind: pipeline
type: docker
name: my-first-build

trigger:
  branch: 
    - test
  event:
    - push
    
steps:
  - name: build
    image: alpine
    enviroment: 
      PWD: ""
    commands:
      - echo "build step executed"
      - apk add gcc
      - pwd
      - $PWD = pwd
  
  - name: compile
    image: gcc
    commands:
      - g++ main.cpp -o program
      - ./program
      
  - name: deploy
    image: alpine
    commands:
      - echo "deploy step executed"
